from . import account_batch_payment
from . import account_batch_payment_address
from . import account_batch_payment_funding
from . import account_batch_payment_us_key
from . import account_journal
from . import account_payment
from . import account_payment_method
from . import account_payment_register
from . import res_partner_bank
from . import wise_recipient_email
